### ISSUE TITLE
Error: "Cloud Resource Manager API has not been used in project" when listing organizations. Invalid error.

### ISSUE THREAD

**Issue by kbroughton** [googleapis/python-resource-manager#129]
I'm trying to do the simple task of listing an org. 
With gcloud I can do
gcloud organizations list

client.search_organizations()
```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "Cloud Resource Manager API has not been used in project 64729511111 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=647295011111 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
	debug_error_string = "{"created":"@1635477214.866780200","description":"Error received from peer ipv4:172.217.28.xxx:443","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Cloud Resource Manager API has not been used in project 647295011111 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=647295011111 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","grpc_status":7}"
>
```

This does not seem to be a valid error as the same credentials and project are able to list the organizations with gcloud.

Also, Developers with the new SDK will expect similar functionality to gcloud since it is written in python. The clients should support the same global options as the gcloud command. The clients to not accept "project" the way all gcloud commands do.

Also, the number of examples for the 100+ repos is super small. I found a total of one page with a real example. Each readme for each repo should have real examples, not a codegen non example with only pip install instructions.
This was hard to find. https://cloud.google.com/compute/docs/tutorials/python-guide

**Comment by parthea** [comment]
I'm going to close this issue as obsolete as a response was provided in https://github.com/googleapis/python-resource-manager/issues/129#issuecomment-954811128. The repository also has autogenerated samples [here](https://github.com/googleapis/python-resource-manager/tree/main/samples/generated_samples).
