### ISSUE TITLE
docs: Add samples for google-cloud-resource-manager

### ISSUE THREAD

**Issue by sunset1234321** [googleapis/python-resource-manager#132]
hope there will be example

**Comment by parthea** [comment]
I've added the docs label as this repository doesn't have [samples](https://github.com/googleapis/python-resource-manager/tree/main/samples) yet.

**Comment by socketbox** [comment]
Please spare future users of this library the frustration I just went through and include (even rudimentary) samples.

**Comment by parthea** [comment]
Auto-generated samples have been added in the `generated_samples` directory: https://github.com/googleapis/python-resource-manager/tree/main/samples/generated_samples. I'm going to close this issue but please feel free to re-open it or create a new issue.
