### ISSUE TITLE
Permission denied even with correct permissions

### ISSUE THREAD

**Issue by cloudmatt** [googleapis/python-resource-manager#148]
#### Environment details

  - OS type and version: `macOS 12.1 (21C52)`
  - Python version: `3.9.9`
  - pip version: `21.3.1`
  - `google-cloud-resource-manager` version: `1.3.3`

#### Issue

I'm getting "permission denied" trying to do something in python that I can do from the google cloud SDK without issue. Unfortunately I have been unable to resolve and begrudgingly came here for help :)

Don't know where the breakdown is between `gcloud` <-> `python` but would appreciate someone taking a look.
  
#### Code example

```python
from google.cloud import resourcemanager

client = resourcemanager.ProjectsClient()
for projects in client.search_projects():
    print(projects)
```
```
(env) ➜  GCP gcloud projects list --limit 1 --format text
---
createTime:     2022-01-04T22:24:23.708Z
lifecycleState: ACTIVE
name:           [SNIPPED]
parent.id:      [SNIPPED]
parent.type:    folder
projectId:      [SNIPPED]
projectNumber:  [SNIPPED]
```
#### Stack trace
```
Traceback (most recent call last):
  File "/Users/matt/tools/GCP/env/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/matt/tools/GCP/env/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/matt/tools/GCP/env/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "Cloud Resource Manager API has not been used in project [ID REMOVED] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=[ID REMOVED] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
        debug_error_string = "{"created":"@1641391604.759377000","description":"Error received from peer ipv4:142.250.191.234:443","file":"src/core/lib/surface/call.cc","file_line":1075,"grpc_message":"Cloud Resource Manager API has not been used in project [ID REMOVED] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=[ID REMOVED] then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","grpc_status":7}"
```

**Comment by busunkim96** [comment]
Hi @cloudmatt,

The client library may be making the request on a project that's different from what `gcloud` is using.  If you haven't already, try following the link in the error details (`https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=[ID REMOVED]`). The link _should_ take you to a page where you can enable the API. 

If that doesn't work, please try running this bit of code to confirm the `project` is what you expect.

```python
import google.auth

credentials, project = google.auth.default()
print(project)
```

https://cloud.google.com/docs/authentication/best-practices-applications has a nice decision tree on how we recommend authenticating in different environments.

**Comment by cloudmatt** [comment]
> Hi @cloudmatt,
> 
> The client library may be making the request on a project that's different from what `gcloud` is using. If you haven't already, try following the link in the error details (`https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=[ID REMOVED]`). The link _should_ take you to a page where you can enable the API.
> 
> If that doesn't work, please try running this bit of code to confirm the `project` is what you expect.
> 
> ```python
> import google.auth
> 
> credentials, project = google.auth.default()
> print(project)
> ```
> 
> https://cloud.google.com/docs/authentication/best-practices-applications has a nice decision tree on how we recommend authenticating in different environments.

Howdy @busunkim96 - thank you for the reply. Using your code snippet and comparing to the `gcloud` output, the projects being used are identical.
```
(env) ➜  GCP python gcp_audit.py
mycompanynameiremoved-staging
(env) ➜  GCP cat gcp_audit.py   
import google.auth

credentials, project = google.auth.default()
print(project)
(env) ➜  GCP gcloud config get-value project
mycompanynameiremoved-staging
```
Additionally, when I `gcloud projects list` it does successfully return all the projects within my OU so I don't think its a perms/authentication issue.

**Comment by cloudmatt** [comment]
Curious if there is any other solutions to try? Would love to have something in python instead of just writing an ugly bash script.

**Comment by ivanmkc** [comment]
I was going to open an issue but I saw this and want to second it.

```
from google.cloud import resourcemanager_v3

client = resourcemanager_v3.ProjectsClient()

projects = client.list_projects()

print(projects)
```

Gives me:
```
google.api_core.exceptions.PermissionDenied: 403 The caller does not have permission
```

My account has the Editor permission.

**Comment by cloudmatt** [comment]
Closing since there is no answers/guidance for this issue.
