### ISSUE TITLE
gcloud auth application-default login vs gcloud auth login

### ISSUE THREAD

**Issue by jnalley** [googleapis/python-resource-manager#17]
Hi! I ran into an issue following the documentation for creating a client.  From the documentation:

> This means that for this API you should always use the credentials provided by the Google Cloud SDK, which you can get by running gcloud auth login.
> 
> Once you run that command, google-cloud-python will automatically pick up the credentials, and you can use the "automatic discovery" feature of the library.

Following those instructions to create a client results in the following error (even though `gcloud auth login` was successful):

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    client = resource_manager.Client()
  File "/Users/jnalley/.virtualenv/lib/python3.8/site-packages/google/cloud/resource_manager/client.py", line 72, in __init__
    super(Client, self).__init__(credentials=credentials, _http=_http)
  File "/Users/jnalley/.virtualenv/lib/python3.8/site-packages/google/cloud/client.py", line 132, in __init__
    credentials, _ = google.auth.default()
  File "/Users/jnalley/.virtualenv/lib/python3.8/site-packages/google/auth/_default.py", line 321, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

I found an entry on [stackoverflow](https://stackoverflow.com/questions/48088841/gcloud-auth-login-saves-to-legacy-credentials-folder) that suggested passing `application-default` when running `gcloud auth`.

Using the command `gcloud auth application-default login` instead of `gcloud auth login` allows me to instantiate the client (although a warning is still displayed indicating that the application authenticated using `user` credentials instead of a service account).

Should the documentation be [updated](https://github.com/jnalley/python-resource-manager/commit/4a59d2a4c95049b8050c1a250838761fc59ea136) to reflect this difference or am I doing something wrong.  Thanks!

**Comment by busunkim96** [comment]
Hi @jnalley,

Yep, it looks like that README is out of date. Would you mind opening a PR from your fork?
