### ISSUE TITLE
documentation is missing permission for `search_projects`

### ISSUE THREAD

**Issue by dandhlee** [googleapis/python-resource-manager#235]
There was an internal bug filed (b/246937743) to show that [`search_projects`](https://github.com/googleapis/python-resource-manager/blob/e242c6336b45a01c04ddbe13e2db51994575013f/google/cloud/resourcemanager_v3/services/projects/client.py#L674-L676) is missing permissions for folks to be able to run the code as needed. The documentation seems to hint at requiring "both" permissions, but it currently only lists `resourcemanager.projects.get`. Could you take a look to see where this is missing?

**Comment by parthea** [comment]
Filed https://issuetracker.google.com/issues/278353656 in the public issue tracker for the Resource Manager API.
