### ISSUE TITLE
Update API docs code samples to use the Cloud client library instead of the low-level Google APIs client library

### ISSUE THREAD

**Issue by wescpy** [googleapis/python-resource-manager#239]
The [Cloud Resource Manager API](https://cloud.google.com/resource-manager) documentation, at least the [Python samples](https://cloud.google.com/resource-manager/docs/creating-managing-projects#python), are using the [Google APIs client libraries](https://developers.google.com/api-client-library) instead of the newer Cloud client libraries ("no link here"*), even though the [code samples in the reference docs do](https://cloud.google.com/python/docs/reference/cloudresourcemanager/latest/google.cloud.resourcemanager_v3.services.projects.ProjectsClient#google_cloud_resourcemanager_v3_services_projects_ProjectsClient_create_project).

* — "no link here" means the docs are also missing a page to introduce the Cloud client libraries, like [this one for Cloud Storage](https://cloud.google.com/storage/docs/reference/libraries).

**Comment by parthea** [comment]
Filed b/253003372

**Comment by parthea** [comment]
I'm going to close this issue as a bug was filed internally.
