### ISSUE TITLE
Some PyPI releases do not have corresponding tags

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-resource-manager#5]
I did a quick pass through the commit log and it's not completely clear which commit belongs to each tag. Many of the tags were from the days of the 'umbrella' package where all packages were released together.

**Comment by tseaver** [comment]
I just created tags for the `v0.{20,22,23,24,25,26,27,28}.0` releases (`v0.21.0` already existed).

I can't find any relevant commit for the PyPI `v0.1.0` [release](https://pypi.org/project/google-cloud-resource-manager/0.0.1/):  that date would appear to correspond to https://github.com/googleapis/google-cloud-python/pull/2270, which was an umbrella release for `google-cloud v0.19.0` (2016-09-19).  https://github.com/googleapis/google-cloud-python/tree/4d66524a57d73742b5fe1f4ca571b305031ea5d2/google/cloud/resource_manager had files in it, but the PyPI release is metadata-only (no downloads).

**Comment by busunkim96** [comment]
Thank you @tseaver!
