### ISSUE TITLE
README versions badge indicates support for Python 2.7, 3.5

### ISSUE THREAD

**Issue by danoscarmike** [googleapis/python-resource-manager#77]
I suspect this is because the [most recent](https://pypi.org/project/google-cloud-resource-manager/) (non-release candidate) release was before we dropped support and that shields.io is keying off the [package metadata](https://github.com/googleapis/python-resource-manager/pull/62/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L69-L72) for that release.

**Comment by tseaver** [comment]
Before making the 1.0 release, we should probably tighten up the Trove classifiers too:

```patch
diff --git a/setup.py b/setup.py
index 711783f..e6567a7 100644
--- a/setup.py
+++ b/setup.py
@@ -70,9 +70,12 @@ setuptools.setup(
         release_status,
         "Intended Audience :: Developers",
         "Operating System :: OS Independent",
+        "Programming Language :: Python",
+        "Programming Language :: Python :: 3",
         "Programming Language :: Python :: 3.6",
         "Programming Language :: Python :: 3.7",
         "Programming Language :: Python :: 3.8",
+        "Programming Language :: Python :: 3.9",
         "Topic :: Internet",
         "Topic :: Software Development :: Libraries :: Python Modules",
     ],
```
