### ISSUE TITLE
ImportError: cannot import name 'resource_manager' from 'google.cloud' (unknown location)

### ISSUE THREAD

**Issue by ireneusz-ptak** [googleapis/python-resource-manager#89]
It seems I'm the first one trying to use the latest version (installed with pipenv: google-cloud-resource-manager==1.0.1):

```
>>> from google.cloud import resource_manager

Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name 'resource_manager' from 'google.cloud' (unknown location)
```

**Comment by parthea** [comment]
HI @ireneusz-ptak,

The latest version 1.x , which includes support for the resource manager v3 API, is significantly different compared with the previous 0.x version. For example, `google.cloud.resourcemanager.Client()` does not exist in 1.x. Regretfully, code needs to be re-written and as a result we have bumped the major version from 0.x to 1.x. The client library docs are available [here](https://googleapis.dev/python/cloudresourcemanager/latest/resourcemanager_v3/services.html). If you prefer to use existing code, please [pin to the last 0.x release 0.30.3](https://pypi.org/project/google-cloud-resource-manager/0.30.3/).

Please can you try the following?

```
>>> from google.cloud import resourcemanager
```

**Comment by parthea** [comment]
Hi @ireneusz-ptak,

I'm going to close this issue but please feel free to re-open it if you have additional questions.

**Comment by ireneusz-ptak** [comment]
No problem, didn't notice the different package name.

**Comment by dinvlad** [comment]
Is there any documentation with examples on how to use the new client?

**Comment by dinvlad** [comment]
For example, I was able to guess how to fetch a project using the new API:
```py3
from google.cloud import resourcemanager

client = resourcemanager.ProjectsClient()
client.get_project(name=f"projects/{project_id}")
```
but could not find a mention of the new project name syntax (`projects/{project_id}`) in the new docs. I was only able to guess it by looking at the [actual](https://cloud.google.com/resource-manager/reference/rest/v3/projects/get) API doc.

**Comment by isimluk** [comment]
> Is there any documentation with examples on how to use the new client?

I only found https://googleapis.dev/python/cloudresourcemanager/latest/index.html

**Comment by isimluk** [comment]
> HI @ireneusz-ptak,
> 
> The latest version 1.x , which includes support for the resource manager v3 API, is significantly different compared with the previous 0.x version. For example, `google.cloud.resource_manager.Client()` does not exist in 1.x. Regretfully, user code needs to be re-written and as a result we have bumped the major version from 0.x to 1.x. The client library docs are available [here](https://googleapis.dev/python/cloudresourcemanager/latest/resourcemanager_v3/services.html). If you prefer to not re-write existing code, please [pin to the last 0.x release 0.30.3](https://pypi.org/project/google-cloud-resource-manager/0.30.3/).
> 

I migrating from older client to the newer one and I noticed that `resourcemanager.projects.list` permission is now required for listing projects. Previous API version did not required any permission for listing the projects. Adding permission to our service accounts may slow things down for people trying to migrate as it adds ops complexity to the change. @parthea, do you have rough idea for how long the old API can be relied upon?

**Comment by dinvlad** [comment]
@isimluk that seems rather weird that it didn't require that permission previously (if there were no other permissions that _were_ required). Are you absolutely sure?

**Comment by isimluk** [comment]
You are right @dinvlad. No new permission is required. I was getting permission error from the new API, but the issue was that I was not able to list projects without specifying the parent organisation. When I supply `parent` attribute to `resourcemanager.projects.ProjectClient.projects_list` I no longer get the permission error.

Thank You for pushing back on this.

**Comment by dinvlad** [comment]
I think the docs linked above are _fine_, if a bit hard to navigate 😄 Personally, I'd like to see some real-world examples of this lib's use here [GoogleCloudPlatform/python-docs-samples](https://github.com/GoogleCloudPlatform/python-docs-samples) or somewhere else, just like for the other libraries. But not a big deal if we don't, just takes time to get used to the new syntax from the docs.

**Comment by fugue-ankush** [comment]
> I think the docs linked above are _fine_, if a bit hard to navigate 😄 Personally, I'd like to see some real-world examples of this lib's use here [GoogleCloudPlatform/python-docs-samples](https://github.com/GoogleCloudPlatform/python-docs-samples) or somewhere else, just like for the other libraries. But not a big deal if we don't, just takes time to get used to the new syntax from the docs.

+1

**Comment by parthea** [comment]
I'm going to close this issue as there are generated samples [here](https://github.com/googleapis/python-resource-manager/tree/main/samples/generated_samples).
